# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:

  - board: cornix_e73
    shield: cornix42_left
    snippet: studio-rpc-usb-uart
    artifact-name: cornix42_left

  - board: cornix_e73
    shield: cornix42_right
    artifact-name: cornix42_right


  - board: cornix_e73
    shield: cornix_dongle dongle_display
    snippet: nrf-dongle studio-rpc-usb-uart
    artifact-name: cornix_dongle

  - board: cornix_e73
    shield: cornix_left
    artifact-name: cornix_left
  # ph left
  - board: cornix_e73
    shield: cornix_ph_left
    artifact-name: cornix_ph_left

  - board: cornix_e73
    shield: cornix_right
    artifact-name: cornix_right

  - board: cornix_e73
    shield: settings_reset
    artifact-name: reset
